name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key_path: private_key.pem
          port: 22
          script: |
            cd /home/ubuntu

            if [ ! -d "react-aws" ]; then
              git clone https://github.com/Ranjitr123/react-aws.git
            fi

            cd react-aws
            git pull origin main

            npm install
            npm run build

            pm2 delete react-app || true
            pm2 start serve --name react-app -- -s build -l 3000
            pm2 save